apiVersion: v1
kind: Pod
metadata:
  name: webui-test-load
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - image: dos65/httperf
    name: main
    command:
    - httperf
    - --server=ad5f57668e41f11e882850612da0c7e9-2039368714.us-west-2.elb.amazonaws.com
    - --uri=/webui-master/
    - --rate=100
    - --num-calls=1000000
